providers = ["php"]

[phases.setup]
# We put nodejs_20 right here in the list so it installs smoothly with PHP!
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "php83Extensions.intl",
    "php83Extensions.zip",
    "php83Extensions.pdo_mysql",
    "php83Extensions.mbstring",
    "nodejs_20"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm install",
    "npm run build"
]