providers = ["php"]

[phases.setup]
nixPkgs = [
    "php84",
    "php84Packages.composer",
    "php84Extensions.intl",
    "php84Extensions.zip",
    "php84Extensions.pdo_pgsql",
    "php84Extensions.pgsql",
    "php84Extensions.mbstring",
    "nodejs_20",
    "nginx" 
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm install",
    "npm run build"
]