providers = ["php", "node"]

[phases.setup]
# This forces Railway to use PHP 8.3 and installs your missing extensions!
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "php83Extensions.intl",
    "php83Extensions.zip",
    "php83Extensions.pdo_mysql",
    "php83Extensions.mbstring"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm install",
    "npm run build"
]